# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  profile-header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.profile.header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: louischarnay
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          
  profile-achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.profile.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: louischarnay
          template: classic
          base: ""
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
